### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by SantiagoValdez** [AndroidBootstrap/android-bootstrap#140]
Hello, and thank you for this awesome project.
I'm having this error on re-running the app.
```
IllegalStateException: Can not perform this action after onSaveInstanceState
```

I was able to solve the problem replacing 
```
fragmentManager.beginTransaction()
                    .replace(R.id.container, new CarouselFragment())
                    .commit();
```
on the MainActivity initScreen method with
```
fragmentManager.beginTransaction()
                    .replace(R.id.container, new CarouselFragment())
                    .commitAllowingStateLoss();
```

Is this a proper solution?

Sorry for bother you, and thanks again for your efforts.

**Comment by felipecsl** [comment]
Can you post the entire stacktrace?
This is usually due to a network response or some kind of asynchronous callback that fired after the activity has finished.
`commitAllowingStateLoss` is more of a palliative fix. You should try to find the root cause and fix it insted.
